---
deployment:
  tasks:
    - export DEPLOYPATH=/home/muse4184/public_html/rab.musaeri.my.id
    - /bin/cp -R application $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R system $DEPLOYPATH
    - /bin/cp -R harviacode $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp .cpanel.yml $DEPLOYPATH    
    - /bin/cp .htaccess $DEPLOYPATH
