---
deployment:
  tasks:
    - export DEPLOYPATH=/home/muse4184/public_html/
    - /bin/cp -R application $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R system $DEPLOYPATH
    - /bin/cp -R harviacode $DEPLOYPATH
    - /bin/cp -R node_modules $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp .cpanel.yml $DEPLOYPATH    
    - /bin/cp .htaccess $DEPLOYPATH
