<?php

if (!defined('BASEPATH'))
exit('No direct script access allowed');

class Projek_rincian_model extends CI_Model
{

    public $table = 'projek_rincian';
    public $id = 'id_rincian';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->select('*, ');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->select('*, ');
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_rincian', $q);
        $this->db->select('*, ');
        $this->db->or_like('id_projek', $q);
        $this->db->or_like('item', $q);
        $this->db->or_like('biaya', $q);
        $this->db->or_like('keterangan', $q);
        $this->db->or_like('status', $q);
        $this->db->or_like('persetujuan', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_rincian', $q);
        $this->db->select('projek_rincian.*,projek.id_projek AS IDprojek,projek.status AS statusP,projek.nomor_projek');
        $this->db->join('projek', 'projek_rincian.id_projek = projek.id_projek','left');
        // $this->db->or_like('id_projek', $q);
        $this->db->or_like('item', $q);
        $this->db->or_like('biaya', $q);
        $this->db->or_like('keterangan', $q);
        // $this->db->or_like('status', $q);
        $this->db->or_like('persetujuan', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Projek_rincian_model.php */
/* Location: ./application/models/Projek_rincian_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-07-30 10:55:00 */
/* http://harviacode.com */